Logical order in make config
Change the order of options in make config to put similar options
together. Update test configs to reflect the change.

[ci all]

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -46,15 +46,23 @@ ifneq (${shell [ -f ${BUILDDIR}/Makefile.inc ] && echo 1 || echo 0},1)
 	@echo "# CPLUSPLUS=${CPLUSPLUS}" >> ${BUILDDIR}/Makefile.inc
 	@echo "# FPP=${FPP}" >> ${BUILDDIR}/Makefile.inc
 	@echo "# LINKER=${LINKER}" >> ${BUILDDIR}/Makefile.inc
+	@echo "# LIBTOOL=${LIBTOOL}" >> ${BUILDDIR}/Makefile.inc
 	@echo "# OPTIM=" >> ${BUILDDIR}/Makefile.inc
 	@echo "# COPTIM=" >> ${BUILDDIR}/Makefile.inc
-	@echo "# DEBUG=${DEBUG}" >> ${BUILDDIR}/Makefile.inc
-	@echo "# LIBTOOL=${LIBTOOL}" >> ${BUILDDIR}/Makefile.inc
 ifdef SAMPLE_DEBUG
 	@echo "# DEBUG=${SAMPLE_DEBUG}" >> ${BUILDDIR}/Makefile.inc
 endif
+	@echo "# DEBUG=${DEBUG}" >> ${BUILDDIR}/Makefile.inc
 	@echo "# CDEBUG=" >> ${BUILDDIR}/Makefile.inc
 endif
+
+# BUILD OPTIONS
+# #############
+
+	@echo
+	@echo "BUILD OPTIONS"
+	@echo "============="
+	@echo
 
 ifndef MATH_LINKOPTS
 	@echo
@@ -72,44 +80,6 @@ ifeq ($(origin EXTRA_LINKOPTS), undefined)
 	@read EXTRA_LINKOPTS; echo "EXTRA_LINKOPTS=$$EXTRA_LINKOPTS" >> ${BUILDDIR}/Makefile.inc
 endif
 
-ifndef HAVE_NETCDF
-	@echo
-	@echo "Please enter directories where NetCDF (and optionally HDF5, if you have NetCDF4) libraries are kept:"
-	@echo "   Default: no NetCDF present"
-	@read NETCDF_LIBDIR && if [[ $$NETCDF_LIBDIR ]] ; then \
-	  echo "NETCDF_LIBDIR=$$NETCDF_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo ; \
-	  found_libnetcdf=0; \
-	  for draw in $$NETCDF_LIBDIR; do \
-	    echo "checking d $$draw"; \
-	    eval d=$$draw; \
-	    if [[ -f $$d/libnetcdf.a || -f $$d/libnetcdf.dylib ]]; then \
-	      found_libnetcdf=1; \
-	      if nm $$d/libnetcdf.{a,dylib} | grep -q deflate; then \
-	       echo "NetCDF version 4 found." ; \
-	       echo "NETCDF4=1" >> ${BUILDDIR}/Makefile.inc ; \
-	      else echo "NetCDF older than version 4 found." ; \
-	       echo "NETCDF4=0" >> ${BUILDDIR}/Makefile.inc; \
-	      fi; \
-	      if nm $$d/libnetcdf.{a,dylib} | grep -q curl; then \
-		echo "NetCDF4 requires libcurl."; \
-		echo "NETCDF4_CURL=1" >> ${BUILDDIR}/Makefile.inc; \
-	      fi; \
-	      break; \
-	    fi; \
-	  done; \
-	  if [ $$found_libnetcdf == 0 ]; then \
-	    echo "No libnetcdf.a found in $$NETCDF_LIBDIR"; \
-	    exit 1; \
-	  fi; \
-	  echo "Please enter directory(ies) where NetCDF (and optionally HDF5, if you have NetCDF4) include files are kept:" ; \
-	  read NETCDF_INCDIR && echo "NETCDF_INCDIR=$$NETCDF_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_NETCDF=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	  echo "HAVE_NETCDF=0" >> ${BUILDDIR}/Makefile.inc;\
-	 fi
-endif
-
 ifndef USE_MAKEDEP
 	@echo
 	@echo "Do you want to use makedep? [y/n]"
@@ -121,48 +91,13 @@ ifndef USE_MAKEDEP
 	  echo "MAKEDEP=makedep.py" >> ${BUILDDIR}/Makefile.inc ; fi
 endif
 
-ifndef HAVE_MDCORE
-	@echo
-	@echo "Do you want to compile with MDCORE Potential support? [y/n]"
-	@echo "   Default: n"
-	@read HAVE_MDCORE_Q && if [[ $$HAVE_MDCORE_Q == 'y' ]]; then \
-	  echo "HAVE_MDCORE=1" >> ${BUILDDIR}/Makefile.inc ; \
-	  	@echo "Please enter directory where the MDCORE Potential libraries are kept:" ;\
-	@read MDCORE_LIBDIR && \
-	  echo "MDCORE_LIBDIR=$$MDCORE_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo ; \
-	  echo "Please enter directory where MDCORE Potential include files are kept:" ; \
-	  read MDCORE_INCDIR && echo "MDCORE_INCDIR=$$MDCORE_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	   echo "HAVE_MDCORE=0" >> ${BUILDDIR}/Makefile.inc ; fi
-endif
+# OPTIONAL INTERNAL FEATURES
+# ##########################
 
-ifndef HAVE_ASAP
 	@echo
-	@echo "Please enter directory where the ASAP library is kept:"
-	@echo "   Default: no ASAP library present"
-	@read ASAP_LIBDIR && if [[ $$ASAP_LIBDIR ]] ; then \
-	  echo "ASAP_LIBDIR=$$ASAP_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_ASAP=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else echo "HAVE_ASAP=0" >> ${BUILDDIR}/Makefile.inc ; fi
-endif
-
-ifndef HAVE_KIM
+	@echo "OPTIONAL INTERNAL FEATURES"
+	@echo "=========================="
 	@echo
-	@echo "Please enter directory where the OpenKIM library is kept:"
-	@echo "   Default: no OpenKIM support"
-	@read KIM_DIR && if [[ $$KIM_DIR ]]; then \
-	  echo "HAVE_KIM=1" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "KIM_DIR=$$KIM_DIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "Turn off KIM test.kim autogeneration capability (useful for OpenKIM pipeline only)? [y/n]"; \
-	  echo "   Default: n"; \
-	  read KIM_NO_AUTOGEN_Q && if [[ $$KIM_NO_AUTOGEN_Q == 'y' ]]; then \
-	    echo "KIM_NO_AUTOGENERATE_TEST_KIM=1" >> ${BUILDDIR}/Makefile.inc ; \
-	   else \
-	    echo "KIM_NO_AUTOGENERATE_TEST_KIM=0" >> ${BUILDDIR}/Makefile.inc ; fi; \
-	 else \
-	  echo "HAVE_KIM=0" >> ${BUILDDIR}/Makefile.inc ; fi; 
-endif
 
 ifndef HAVE_CP2K
 	@echo
@@ -214,42 +149,6 @@ ifndef HAVE_FX
 	   echo "HAVE_FX=0" >> ${BUILDDIR}/Makefile.inc ; fi	
 endif
 
-ifndef HAVE_GAP
-	@echo
-	@if [[ ! -d src/GAP ]] ; then \
-	  echo "GAP sources must be acquired separately and placed in the src/GAP subdirectory."; \
-	 fi
-	@echo "Do you want to compile with GAP prediction support ? [y/n]"
-	@echo "   Default: n"
-	@read HAVE_GAP_Q && if [[ $$HAVE_GAP_Q == 'y' ]]; then \
-	  echo "HAVE_GAP=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	   echo "HAVE_GAP=0" >> ${BUILDDIR}/Makefile.inc ; fi
-endif
-
-ifndef HAVE_GAP_FILLER
-	@echo
-	@if [[ ! -d src/GAP-filler ]] ; then \
-	  echo "GAP training sources must be acquired separately and placed in the src/GAP-filler subdirectory."; \
-	 fi
-	@echo "Do you want to compile with GAP training support ? [y/n]"
-	@echo "   Default: n"
-	@read HAVE_GAP_FILLER_Q && if [[ $$HAVE_GAP_FILLER_Q == 'y' ]]; then \
-	  echo "HAVE_GAP_FILLER=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	   echo "HAVE_GAP_FILLER=0" >> ${BUILDDIR}/Makefile.inc ; fi
-endif
-
-ifndef HAVE_QR
-	@echo
-	@echo "Do you want to turn on QR decomposition for some GAP operations? [y/n]"
-	@echo "   Default: y"
-	@read HAVE_QR_Q && if [[ $$HAVE_QR_Q == 'n' ]]; then \
-	  echo "HAVE_QR=0" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	   echo "HAVE_QR=1" >> ${BUILDDIR}/Makefile.inc ; fi
-endif
-
 ifndef HAVE_LOTF
 	@echo
 	@echo "Do you want to compile with Learn-on-the-fly (LOTF) support? [y/n]"
@@ -290,19 +189,48 @@ ifndef HAVE_QC
 	   echo "HAVE_QC=0" >> ${BUILDDIR}/Makefile.inc ; fi
 endif
 
-ifndef HAVE_CGAL
+# OPTIONAL FEATURES (EXTRA CODE REQUIRED)
+# #######################################
+
 	@echo
-	@echo "Please enter directories where CGAL libraries are kept:"
-	@echo "   Default: no CGAL present"
-	@read CGAL_LIBDIR && if [[ $$CGAL_LIBDIR ]] ; then \
-	  echo "CGAL_LIBDIR=$$CGAL_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo ; \
-	  echo "Please enter directory where CGAL include files are kept:" ; \
-	  read CGAL_INCDIR && echo "CGAL_INCDIR=$$CGAL_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_CGAL=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	  echo "HAVE_CGAL=0" >> ${BUILDDIR}/Makefile.inc;\
+	@echo "OPTIONAL FEATURES (EXTRA CODE REQUIRED)"
+	@echo "======================================="
+	@echo
+
+ifndef HAVE_GAP
+	@echo
+	@if [[ ! -d src/GAP ]] ; then \
+	  echo "GAP sources must be acquired separately and placed in the src/GAP subdirectory."; \
 	 fi
+	@echo "Do you want to compile with GAP prediction support ? [y/n]"
+	@echo "   Default: n"
+	@read HAVE_GAP_Q && if [[ $$HAVE_GAP_Q == 'y' ]]; then \
+	  echo "HAVE_GAP=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	   echo "HAVE_GAP=0" >> ${BUILDDIR}/Makefile.inc ; fi
+endif
+
+ifndef HAVE_GAP_FILLER
+	@echo
+	@if [[ ! -d src/GAP-filler ]] ; then \
+	  echo "GAP training sources must be acquired separately and placed in the src/GAP-filler subdirectory."; \
+	 fi
+	@echo "Do you want to compile with GAP training support ? [y/n]"
+	@echo "   Default: n"
+	@read HAVE_GAP_FILLER_Q && if [[ $$HAVE_GAP_FILLER_Q == 'y' ]]; then \
+	  echo "HAVE_GAP_FILLER=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	   echo "HAVE_GAP_FILLER=0" >> ${BUILDDIR}/Makefile.inc ; fi
+endif
+
+ifndef HAVE_QR
+	@echo
+	@echo "Do you want to turn on QR decomposition for some GAP operations? [y/n]"
+	@echo "   Default: y"
+	@read HAVE_QR_Q && if [[ $$HAVE_QR_Q == 'n' ]]; then \
+	  echo "HAVE_QR=0" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	   echo "HAVE_QR=1" >> ${BUILDDIR}/Makefile.inc ; fi
 endif
 
 ifndef HAVE_THIRDPARTY
@@ -314,19 +242,6 @@ ifndef HAVE_THIRDPARTY
 	  echo "   Not found. " ; \
 	  echo "HAVE_THIRDPARTY=0" >> ${BUILDDIR}/Makefile.inc ; \
 	fi
-endif
-
-ifndef HAVE_METIS
-	@echo
-	@echo "Please enter directories where METIS libraries are kept:"
-	@echo "   Default: no METIS present"
-	@read METIS_LIBDIR && if [[ $$METIS_LIBDIR ]] ; then \
-	  echo "METIS_LIBDIR=$$METIS_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo ; \
-	  echo "HAVE_METIS=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else \
-	  echo "HAVE_METIS=0" >> ${BUILDDIR}/Makefile.inc;\
-	 fi
 endif
 
 ifndef HAVE_SCME
@@ -372,6 +287,123 @@ ifndef HAVE_MBD
 	   else \
 	     echo "HAVE_MBD=0" >> ${BUILDDIR}/Makefile.inc ; \
 	   fi
+endif
+
+# OPTIONAL EXTERNAL LIBRARIES
+#############################
+
+	@echo
+	@echo "OPTIONAL EXTERNAL LIBRARIES"
+	@echo "==========================="
+	@echo
+
+
+ifndef HAVE_NETCDF
+	@echo
+	@echo "Please enter directories where NetCDF (and optionally HDF5, if you have NetCDF4) libraries are kept:"
+	@echo "   Default: no NetCDF present"
+	@read NETCDF_LIBDIR && if [[ $$NETCDF_LIBDIR ]] ; then \
+	  echo "NETCDF_LIBDIR=$$NETCDF_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo ; \
+	  found_libnetcdf=0; \
+	  for draw in $$NETCDF_LIBDIR; do \
+	    echo "checking d $$draw"; \
+	    eval d=$$draw; \
+	    if [[ -f $$d/libnetcdf.a || -f $$d/libnetcdf.dylib ]]; then \
+	      found_libnetcdf=1; \
+	      if nm $$d/libnetcdf.{a,dylib} | grep -q deflate; then \
+	       echo "NetCDF version 4 found." ; \
+	       echo "NETCDF4=1" >> ${BUILDDIR}/Makefile.inc ; \
+	      else echo "NetCDF older than version 4 found." ; \
+	       echo "NETCDF4=0" >> ${BUILDDIR}/Makefile.inc; \
+	      fi; \
+	      if nm $$d/libnetcdf.{a,dylib} | grep -q curl; then \
+		echo "NetCDF4 requires libcurl."; \
+		echo "NETCDF4_CURL=1" >> ${BUILDDIR}/Makefile.inc; \
+	      fi; \
+	      break; \
+	    fi; \
+	  done; \
+	  if [ $$found_libnetcdf == 0 ]; then \
+	    echo "No libnetcdf.a found in $$NETCDF_LIBDIR"; \
+	    exit 1; \
+	  fi; \
+	  echo "Please enter directory(ies) where NetCDF (and optionally HDF5, if you have NetCDF4) include files are kept:" ; \
+	  read NETCDF_INCDIR && echo "NETCDF_INCDIR=$$NETCDF_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "HAVE_NETCDF=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	  echo "HAVE_NETCDF=0" >> ${BUILDDIR}/Makefile.inc;\
+	 fi
+endif
+
+ifndef HAVE_MDCORE
+	@echo
+	@echo "Please enter directories where MDCORE libraries are kept:"
+	@echo "   Default: no MDCORE present"
+	@read MDCORE_LIBDIR && if [[ $$MDCORE_LIBDIR ]] ; then \
+	  echo "MDCORE_LIBDIR=$$MDCORE_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo ; \
+	  echo "Please enter directory where MDCORE include files are kept:" ; \
+	  read MDCORE_INCDIR && echo "MDCORE_INCDIR=$$MDCORE_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "HAVE_MDCORE=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	  echo "HAVE_MDCORE=0" >> ${BUILDDIR}/Makefile.inc;\
+	 fi
+endif
+
+ifndef HAVE_ASAP
+	@echo
+	@echo "Please enter directory where the ASAP library is kept:"
+	@echo "   Default: no ASAP library present"
+	@read ASAP_LIBDIR && if [[ $$ASAP_LIBDIR ]] ; then \
+	  echo "ASAP_LIBDIR=$$ASAP_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "HAVE_ASAP=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else echo "HAVE_ASAP=0" >> ${BUILDDIR}/Makefile.inc ; fi
+endif
+
+ifndef HAVE_KIM
+	@echo
+	@echo "Please enter directory where the OpenKIM library is kept:"
+	@echo "   Default: no OpenKIM support"
+	@read KIM_DIR && if [[ $$KIM_DIR ]]; then \
+	  echo "KIM_DIR=$$KIM_DIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "Turn off KIM test.kim autogeneration capability (useful for OpenKIM pipeline only)? [y/n]"; \
+	  echo "   Default: n"; \
+	  read KIM_NO_AUTOGEN_Q && if [[ $$KIM_NO_AUTOGEN_Q == 'y' ]]; then \
+	    echo "KIM_NO_AUTOGENERATE_TEST_KIM=1" >> ${BUILDDIR}/Makefile.inc ; \
+	   else \
+	    echo "KIM_NO_AUTOGENERATE_TEST_KIM=0" >> ${BUILDDIR}/Makefile.inc ; fi; \
+	  echo "HAVE_KIM=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	  echo "HAVE_KIM=0" >> ${BUILDDIR}/Makefile.inc ; fi; 
+endif
+
+ifndef HAVE_CGAL
+	@echo
+	@echo "Please enter directories where CGAL libraries are kept:"
+	@echo "   Default: no CGAL present"
+	@read CGAL_LIBDIR && if [[ $$CGAL_LIBDIR ]] ; then \
+	  echo "CGAL_LIBDIR=$$CGAL_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo ; \
+	  echo "Please enter directory where CGAL include files are kept:" ; \
+	  read CGAL_INCDIR && echo "CGAL_INCDIR=$$CGAL_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "HAVE_CGAL=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	  echo "HAVE_CGAL=0" >> ${BUILDDIR}/Makefile.inc;\
+	 fi
+endif
+
+ifndef HAVE_METIS
+	@echo
+	@echo "Please enter directories where METIS libraries are kept:"
+	@echo "   Default: no METIS present"
+	@read METIS_LIBDIR && if [[ $$METIS_LIBDIR ]] ; then \
+	  echo "METIS_LIBDIR=$$METIS_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo ; \
+	  echo "HAVE_METIS=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else \
+	  echo "HAVE_METIS=0" >> ${BUILDDIR}/Makefile.inc;\
+	 fi
 endif
 
 ifndef HAVE_LMTO_TBE
