Prevent from asking FoX question twice on fresh checkout
git-svn-id: svn+ssh://cvs/home/jrk33/repo/trunk/QUIP@7809 9aeadc09-fa51-0410-b5d8-e5c65b1e449c

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -68,8 +68,8 @@ ifndef FOX_LIBDIR
 	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/ThirdParty/FoX-4.0.3/objs.${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
 	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
 endif
-ifneq (${shell [ -f ${FOX_LIBDIR}/libFoX_common.a ] && echo 1 || echo 0},1)
-	@echo "FoX libraries not found in directory ${FOX_LIBDIR}"
+ifneq (${shell [ -d ${FOX_LIBDIR}/.. ] && echo 1 || echo 0},1)
+	@echo "FoX not found in directory ${FOX_LIBDIR}"
 	@echo "Please enter directory where FoX libraries are kept:"
 	@echo "   Default: use included version ${FOX}"
 	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
