fixed FoX stuff. 'make' works now after a deepclean

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -54,35 +54,35 @@ ifndef MATH_LINKOPTS
 	  echo "MATH_LINKOPTS=${DEFAULT_MATH_LINKOPTS}" >> ${BUILDDIR}/Makefile.inc ; \
 	  else echo "MATH_LINKOPTS=$$MATH_LINKOPTS" >> ${BUILDDIR}/Makefile.inc ; fi
 endif
-ifndef FOX_LIBDIR
-	@echo
-	@echo "Please enter directory where FoX libraries are kept:"
-	@echo "   Default: use included version ${FOX}"
-	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
-	  echo "FOX_LIBDIR=$$FOX_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo ; \
-	  echo "Please enter directory where FoX include files are kept:" ; \
-	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/FoX-4.0.3/objs."'$${QUIP_ARCH}'"/lib" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/FoX-4.0.3/objs."'$${QUIP_ARCH}'"/finclude" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
-else
-   ifneq (${shell [ -d $$(dirname $$(dirname ${FOX_LIBDIR})) ] && echo 1 || echo 0},1)
-	@echo "FoX not found in directory ${FOX_LIBDIR}"
-	@echo "Please enter directory where FoX libraries are kept:"
-	@echo "   Default: use included version ${FOX}"
-	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
-	  echo "FOX_LIBDIR=$$FOX_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo ; \
-	  echo "Please enter directory where FoX include files are kept:" ; \
-	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/FoX-4.0.3/objs.$${QUIP_ARCH}/lib" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/FoX-4.0.3/objs.$${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
-   endif
-endif
+# ifndef FOX_LIBDIR
+# 	@echo
+# 	@echo "Please enter directory where FoX libraries are kept:"
+# 	@echo "   Default: use included version ${FOX}"
+# 	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
+# 	  echo "FOX_LIBDIR=$$FOX_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo ; \
+# 	  echo "Please enter directory where FoX include files are kept:" ; \
+# 	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
+# 	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/src/FoX-4.0.3/objs."'$${QUIP_ARCH}'"/lib" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/src/FoX-4.0.3/objs."'$${QUIP_ARCH}'"/finclude" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
+# else
+#    ifneq (${shell [ -d $$(dirname $$(dirname ${FOX_LIBDIR})) ] && echo 1 || echo 0},1)
+# 	@echo "FoX not found in directory ${FOX_LIBDIR}"
+# 	@echo "Please enter directory where FoX libraries are kept:"
+# 	@echo "   Default: use included version ${FOX}"
+# 	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
+# 	  echo "FOX_LIBDIR=$$FOX_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo ; \
+# 	  echo "Please enter directory where FoX include files are kept:" ; \
+# 	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
+# 	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/src/FoX-4.0.3/objs.$${QUIP_ARCH}/lib" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/src/FoX-4.0.3/objs.$${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
+# 	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
+#    endif
+#endif
 ifndef HAVE_NETCDF
 	@echo
 	@echo "Please enter directories where NetCDF (and optionally HDF5, if you have NetCDF4) libraries are kept:"
