Move third-party libraries into new top-level directory "ThirdParty"
git-svn-id: svn+ssh://cvs/home/jrk33/repo/trunk/QUIP@7806 9aeadc09-fa51-0410-b5d8-e5c65b1e449c

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -64,8 +64,22 @@ ifndef FOX_LIBDIR
 	  echo "Please enter directory where FoX include files are kept:" ; \
 	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
 	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
-	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/FoX-4.0.3/objs.${QUIP_ARCH}/lib" >> ${BUILDDIR}/Makefile.inc ; \
-	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/FoX-4.0.3/objs.${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
+	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/ThirdParty/FoX-4.0.3/objs.${QUIP_ARCH}/lib" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/ThirdParty/FoX-4.0.3/objs.${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
+endif
+ifneq (${shell [ -f ${FOX_LIBDIR}/libFoX_common.a ] && echo 1 || echo 0},1)
+	@echo "FoX libraries not found in directory ${FOX_LIBDIR}"
+	@echo "Please enter directory where FoX libraries are kept:"
+	@echo "   Default: use included version ${FOX}"
+	@read FOX_LIBDIR && if [[ $$FOX_LIBDIR ]] ; then \
+	  echo "FOX_LIBDIR=$$FOX_LIBDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo ; \
+	  echo "Please enter directory where FoX include files are kept:" ; \
+	  read FOX_INCDIR && echo "FOX_INCDIR=$$FOX_INCDIR" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "HAVE_EXTERNAL_FOX=1" >> ${BUILDDIR}/Makefile.inc ; \
+	 else echo "FOX_LIBDIR="'$${QUIP_ROOT}'"/ThirdParty/FoX-4.0.3/objs.${QUIP_ARCH}/lib" >> ${BUILDDIR}/Makefile.inc ; \
+	  echo "FOX_INCDIR="'$${QUIP_ROOT}'"/ThirdParty/FoX-4.0.3/objs.${QUIP_ARCH}/finclude" >> ${BUILDDIR}/Makefile.inc ; \
 	  echo "HAVE_EXTERNAL_FOX=0" >> ${BUILDDIR}/Makefile.inc ; fi
 endif
 ifndef HAVE_NETCDF
