Move GP kernel functions in GPUI.py into their own class.  Can probably be done    better by someone who knows python. Better handling of failed checkouts in utility_scripts/tag_QUIP_latest_good_version
git-svn-id: svn+ssh://cvs/home/jrk33/repo/trunk/QUIP@9468 9aeadc09-fa51-0410-b5d8-e5c65b1e449c

diff --git a/utility_scripts/tag_QUIP_latest_good_version b/utility_scripts/tag_QUIP_latest_good_version
--- a/utility_scripts/tag_QUIP_latest_good_version
+++ b/utility_scripts/tag_QUIP_latest_good_version
@@ -186,7 +186,16 @@ test_version HEAD
 status_no_Failed $make_status; make_ok=$?
 status_no_Failed $quippy_status; quippy_ok=$?
 
-cd QUIP_test; cur_rev=`svnversion -n`; cd ..
+if [ -d QUIP_test ]; then
+   cd QUIP_test; cur_rev=`svnversion -n`; cd ..
+else
+   rm -f mail_msg.txt
+   (echo "testing of HEAD version failed to even create a QUIP_test directory"; echo "ls -l"; ls -l) > mail_msg.txt
+   mutt -s "QUIP autobuild failed" `for f in $failed_list; do echo "-a $f "; done` `for c in $failed_mails; do echo "-c $c "; done` ${MAILS} < mail_msg.txt
+   rm -f $LOCKFILE
+   exit 4
+fi
+
 HEAD_rev=${cur_rev}
 echo "HEAD($cur_rev) make $make_status quippy test $quippy_status"
 echo "HEAD($cur_rev) make $make_status quippy test $quippy_status" > ${REPORT_FILE}
